---
# Playbook to deploy Centos VMs on vCenter
# Requires an inventory file with group called: [wlvm]. Uses the role deploycentosnetsim
#
# Created by: Bar McHugh
# Written: April 2019
# Updated: 
#


- hosts: wlvm 
  gather_facts: no 
  serial: 20
  roles:
  - deploycentosnetsim
  
  vars_prompt:
    - name: "cluster_input"
      prompt: "What Cluster will these be deployed in? e.g. Netsim4-POD7-Cluster1, Netsim5-POD7-CL1 "
      private: no
  vars:
    wlvm: yes
    netsim_vm: no
    centos_vm_template: centos75
    ifcfg_name: ifcfg-ens160
    run_fixes: no
