---
# group_vars used in most cases as mulitple roles use the same common variables accross the enviroment

vip_prefix: 22        # /22 (=1024) Value to specify the amount of VIPs per Server, and this would usually determine the range_file_number variable = 4 (as 4 x 256 = 1024) #
vip_CIDR: 22        # The actual subnet to be used for the VIP network. Mostly will always be the same as {{vip_prefix}}, but will determine xxx.xxx.xxx.xxx/{{vip_CIDR}}. 
range_file_number: 4  # This is calculate based on how many /24 network are in vip_prefix value. Range files can only have /24's defined. Centos limitation #
ipv6_vip_prefix: 80
#ipv6_vip_prefix: 96  # Value for Openstack Instances
ipv6_vip_count: 1000
#vip_count: 1023
 
ifcfg_folder_path: "/etc/sysconfig/network-scripts/"
device_name: ens160
#device_name: eth0  # Value for Openstack Instances

config_files:
  - name: "/etc/ssh/sshd_config"
    regexp: "^ListenAddress {{ lookup('dig', '{{ inventory_hostname }}' )}}"
    line: "ListenAddress {{ lookup('dig', '{{ inventory_hostname }}' )}}"
  - name: "/etc/ssh/sshd_config"
    regexp: "^ListenAddress 127.0.0.1"
    line: "ListenAddress 127.0.0.1"
  - name: "/etc/ssh/sshd_config"
    regexp: "^MaxStartups 200"
    line: "MaxStartups 200"
  - name: "/etc/security/limits.conf"
    regexp: "hard    nofile             64000"
    line: "*               hard    nofile             64000"
  - name: "/etc/security/limits.conf"
    regexp: "soft    nofile             64000"
    line: "*               soft    nofile             64000"
  - name: "/etc/security/limits.d/20-nproc.conf"
    regexp: "^.          soft    nproc"
    line: "*          soft    nproc     516359"
  - name: "/etc/security/limits.d/20-nproc.conf"
    regexp: "^root       soft    nproc"
    line: "root       soft    nproc     unlimited"
  - name: "/etc/sysctl.conf"
    regexp: "^kernel.pid_max = [0-9]"
    line: "kernel.pid_max = 65536"
  - name: "/etc/sysctl.conf"
    regexp: "^kernel.threads-max = [0-9]"
    line: "kernel.threads-max = 1032718"
  - name: "/etc/sysctl.conf"
    regexp: "^fs.inotify.max_user_watches = [0-9]"
    line: "fs.inotify.max_user_watches = 65536"
  - name: "/etc/profile"
    regexp: "^export http_proxy="
    line: "export http_proxy=159.107.173.253:3128"
  - name: "/etc/profile"
    regexp: "^export https_proxy="
    line: "export https_proxy=159.107.173.253:3128"

rsh_files:
  - name: "/etc/pam.d/rsh"
    regexp: "pam_securetty.so"
    line: "#auth       required     pam_securetty.so"
  - name: "/etc/pam.d/rsh"
    regexp: "pam_rhosts.so"
    line: "auth       required     pam_rhosts.so promiscuous"
  - name: "/etc/pam.d/rlogin"
    regexp: "pam_securetty.so"
    line: "#auth       required     pam_securetty.so"
  - name: "/etc/pam.d/rexec"
    regexp: "pam_securetty.so"
    line: "#auth       required     pam_securetty.so"
  - name: "/etc/securetty"
    regexp: "rsh"
    line: "rsh"
  - name: "/etc/securetty"
    regexp: "rexec"
    line: "rexec"
  - name: "/etc/securetty"
    regexp: "rlogin"
    line: "rlogin"
  - name: "/etc/selinux/config"
    regexp: "SELINUX=disabled"
    line: "SELINUX=disabled"
  - name: "/etc/selinux/config"
    regexp: "SELINUX=enforcing"
    line: "#SELINUX=enforcing"

sudoer_file:
  - name: "/etc/sudoers"
    regexp: "^Defaults r"
    line: "Defaults rootpw"



package:
  - bind-utils
  - zip
  - wget
  - curl
  - expect
  - ntp
  - unzip
  - perl-devel
  - perl-Switch
  - dos2unix
  - expect
  - cpan
  - perl-Test-Simple
  - bc
  - glibc
  - mlocate
  - ncurses-libs-5.9-14.20130511.el7_4.i686
  - zlib-devel
  - zlib
  - readline-devel.i686
  - openssl-libs.i686
  - openssl
  - ed
  - xterm
  - lsof
  - epel-release
  #- perl-Net-OpenSSH
  - openldap
  - openldap-clients
  - openldap-servers
  - rsh
  - rsh-server
  - readline-static.x86_64
  #- libreadline5 - Installed by transferring rpm
  - psmisc
  - vim
  - perl-Compress-Raw-Zlib
  - perl-IO-Compress
  - xauth
  - libXext.x86_64
  - libXrender.x86_64
  - libXtst.x86_64
  - libXext.i686
  - libXtst-devel.i686
  - libXrender-devel.i686


wlvm_package:
  - wget
  - rsync
  - python-setuptools
  - sysstat
  - vim

manual_package:
  - "libreadline5-32bit-5.2-147.9.13.x86_64.rpm"

package_dest: "/tmp/"
