---
# group_vars used in most cases as mulitple roles use the same common variables accross the enviroment

vip_prefix: 22
range_file_number: 4  # This is calculate based on how many /24 network are in vip_prefix value. Range files can only have /24's defined. Centos limitation #
vip_count: 1023
ifcfg_folder_path: "/etc/sysconfig/network-scripts/"

package:
  - bind-utils
  - zip
  - wget
  - curl
  - expect
  - ntp


