---
- name: Set Up main interface and IPv6
  template:
    src: ifcfg.j2
    dest: "{{ifcfg_folder_path}}{{ifcfg_name}}"
  register: ifcfg_state
  tags: subinterface
 
 
- name: Create Sub Interfaces using Range Files
  template: src=range.j2 dest="{{ifcfg_folder_path}}{{ifcfg_name}}-range{{item}}"
  #template: src=range.j2 dest=/tmp/{{ifcfg_name}}-range{{item}}
  loop: "{{range(0, range_file_number ) | list }}"   # range_file_number is defined in the role vars main.yml file #
  #connection: local
  register: ifcfg_range_state
  tags:
    - subinterface
    - range
 
- name: Configure Main interface
  lineinfile:
    path: "{{ifcfg_folder_path}}{{ifcfg_name}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    insertafter: '^BOOTPROTO'
  with_items:
    - {regexp: '^ARP', line: 'ARPCHECK=no'}
    - {regexp: '^NM_CONTROLLED', line: 'NM_CONTROLLED=no'}
  tags: subinterface

# Restart the Network to apply IP addresses & routes.
- name: Restart Network Service
  service:
    name: network
    state: restarted
  when: ifcfg_state is changed or ifcfg_range_state is changed
