---
- name: Allow rsh for root
  lineinfile:
    path: "{{item.name}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items: "{{rsh_files}}"

- name: Start & Enable rsh,rlogin,rexec
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
    - rsh.socket
    - rlogin.socket
    - rexec.socket

- name: Create if not created ~/.rhosts file and Set permissions & copy in content
  copy:
    content: "+ +"
    dest: "/{{item}}/.rhosts"
    owner: "{{item}}"
    group: "{{item}}"
    mode: "0600"
  with_items:
    - root
    - netsim

- name: Create /netsim directory
  file:
    path: /netsim
    state: directory 
    owner: netsim
    group: netsim

- name: Create /pms_tmpfs directory
  file:
    path: /pms_tmpfs
    state: directory 
    owner: netsim
    group: netsim
    mode: "0777"

- name: Change sudo password to root pw
  lineinfile:
    path: "{{item.name}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items: "{{sudoer_file}}"

- name: Start & Enable slapd
  systemd:
    name: slapd
    state: started
    enabled: yes

- name: Check value of /proc/sys/kernel/pid_max
  command: "sysctl kernel.pid_max"
  register: pid_max
  changed_when: false

- name: Set /proc/sys/kernel/pid_max to 65536 - Skips if already at 65536
  copy:
    content: "65536"
    dest: /proc/sys/kernel/pid_max
    unsafe_writes: yes
  when: pid_max.stdout | regex_search("[0-9]{1,5}$") | int < 65535
