---
- name: Create /netsim directory
  file:
    path: /netsim
    state: directory 
    owner: netsim
    group: netsim

- name: Change sudo password to root pw
  lineinfile:
    path: "{{item.name}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items: "{{sudoer_file}}"

