- name: Set up Proxy
  lineinfile:
    path: "/etc/yum.conf"
    regexp: "proxy="
    line: "proxy={{ http_proxy }}"

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install {{ package }}
  yum:
    name: "{{ package }}"
    state: present

- name: Transfer Package
  copy:
    src: "{{ item }}"
    dest: "{{ package_dest }}{{ item }}"
  with_items: "{{manual_package}}"

- name: Install {{ manual_package }}
  yum:
    name: "{{ package_dest }}{{item}}"
    state: present
  with_items: "{{manual_package}}"
