---
- name: Disable Firewalld
  systemd:
    name: firewalld
    enabled: no

- name: Stop Firewalld
  systemd:
    name: firewalld
    state: stopped

- name: Disable NetworkManger
  systemd:
    name: NetworkManager
    enabled: no

- name: Stop NetworkManager
  systemd:
    name: NetworkManager
    state: stopped


- name: Enable Network
  systemd: 
    name: network
    enabled: yes

- name: Start Network
  systemd:
    name: network
    state: started

- name: Start & Enable slapd
  systemd:
    name: slapd
    state: started
    enabled: yes

- name: Customise /proc/sys/kernel/pid_max
  shell: 'echo "65536" > /proc/sys/kernel/pid_max'
  when: lookup('file', '/proc/sys/kernel/pid_max') < 65536

- name: Customise config files as define in VARs
  lineinfile:
    path: "{{item.name}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items: "{{config_files}}"

- name: Allow rsh for root
  lineinfile:
    path: "{{item.name}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items: "{{rsh_files}}"
  when: netsim_vm
